# NoFlyZone version: 1.3 Main Configuration
# 
# List regions below that will disable players from flying when they enter them

no_fly_worlds: []
no_fly_message: '&cNo flying here!'
auto_fly_message: '&aYour flight has been toggled on!'
no_fly_regions:
  world:
  - dropparty
